language: node_js
sudo: false
node_js:
  - 12
install: true
script:
  - npm install
  - npm run build
  - mv index-linux bitabase-linux-$TRAVIS_TAG-amd64
  - mv index-macos bitabase-darwin-$TRAVIS_TAG-amd64
  - mv index-win.exe bitabase-windows-$TRAVIS_TAG.exe
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - bitabase-linux-$TRAVIS_TAG-amd64
    - bitabase-darwin-$TRAVIS_TAG-amd64
    - bitabase-windows-$TRAVIS_TAG.exe
  on:
    repo: bitabase/bitabase
    tags: true
