language: node_js
sudo: false
node_js:
  - 12.16.3
install: true
script:
  - git clone https://github.com/geekuillaume/pkg.git
  - cd pkg
  - npm i
  - npm link
  - cd ../
  - npm install
  - node downloadRqlite.js
  - ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=win32 --target_arch=x64 --target=12.16.3
  - ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --target_arch=x64 --target=12.16.3
  - ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=darwin --target_arch=x64 --target=12.16.3
  - npm run build
  - mv dist/index-linux bitabase-linux-$TRAVIS_TAG-amd64
  - mv dist/index-macos bitabase-darwin-$TRAVIS_TAG-amd64
  - mv dist/index-win.exe bitabase-windows-$TRAVIS_TAG-amd64.exe
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - bitabase-linux-$TRAVIS_TAG-amd64
    - bitabase-darwin-$TRAVIS_TAG-amd64
    - bitabase-windows-$TRAVIS_TAG-amd64.exe
  on:
    repo: bitabase/bitabase
    tags: true
